[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
# Cambiamos $PORT por ${PORT} para asegurar que se lea como número
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3